
module.exports = {
  'primary-color': '#E1E1E1',
  'primary-backgroundColor': '#000',
  'primary-selection-backgroundColor': '#1467b1',
  'primary-hover-backgroundColor': '#10518a',
  'secondary-color': '#adacac',
  'secondary-backgroundColor': '#1D1D1D',
  'secondary-hover-backgroundColor': '#3a465f',
  'alternative-backgroundColor': '#296ba7',
  'table-selection-backgroundColor': '#151515',
  'scrollBar-thumb-backgroundColor': '#52565A',
  'scrollBar-thumb-hover-backgroundColor': '#A9ABAD',
  'scrollBar-track-backgroundColor': '#282829',
  'toolbar-popup-backgroundColor': '#424c57',
  'tab-titles-backgroundColor': '#1D1D1D',
  'tab-pane-backgroundColor': '#1D1D1D',
  'tab-title-backgroundColor': '#121212',
  'controls-backgroundColor': '#2A2A2A',
  'controls-color': '#AFAFAF',
  'controls-borderColor': '#505050',
  'preview-backgroundColor': '#1D1D1D',
  'property-title-color': '#AFAFAF',
  'property-title-backgroundColor': '#353434',
  'property-title-expanded-color': '#FFFFFF',
  'property-title-expanded-backgroundColor': '#296ba7',
  'entityTree-button-color': '#fbfbfb',
  'entityTree-button-borderColor': '#FFFFFF',
  'entityTree-button-hover-color': '#fbfbfb',
  'entityTree-button-hover-backgroundColor': '#3a465f',
  'contextMenu-backgroundColor': '#3a3a3a',
  'contextMenu-button-color': '#bdbaba',
  'entityFinder-input-hover-borderColor': '#d9d9d9',
  'entityFinder-results-item-active-backgroundColor': '#1467b1',
  'popover-backgroundColor': '#3a3a3a'
}
